### ISSUE TITLE
Create a UI Page to Display the Point System

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#11]
We need a new page on the site that displays the point system for Hacktoberfest contributions. The point system is used to allocate points to different types of contributions (e.g., documentation, bug fixes, etc.). The page should be built using React, and it will display the following point system:

- Documentation: 1 point
- Bug fix: 2 points
- Level 1 contribution: 3 points
- Level 2 contribution: 5 points
- Level 3 contribution: 8 points

### Requirements:
- Create a new page that shows the point system using a table or other user-friendly layout.
- The page should be styled with tailwindcss, following the existing site's theme.
- Ensure the page is responsive and accessible.
  
### Acceptance Criteria:
- The page successfully displays the point system in a readable format.
- The page should be integrated into the existing site's navigation.

### Additional Notes:
- Discuss any design improvements if needed, but keep the UI clean and easy to understand.
- Ensure that the component or page can be reused or updated easily if the point system changes.

**Comment by Ayushkalathiya** [comment]
can you assign me this task @jalaym825

**Comment by jalaym825** [comment]
> can you assign me this task @jalaym825

It's already closed and live on website. You can work on points page.
