### ISSUE TITLE
Nevigate to FAQs

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/club-gamma-frontend#113]
### Need to Fix it..

![image](https://github.com/user-attachments/assets/6af75eec-faf3-4faf-bad8-0a247381ef79)

**Comment by Meetpidev** [comment]
@jalaym825 The problem is that there is separte rout "/hacktoberfest2024" for the Hactoberfest details.. and when we are in this and click on FAQs.. its redirect to Home Page and Dont shw FAQs section.. 

Second Problem is that after clicking FAQs when we are in Hactoberfest section... that mini-nvarbar  is also disappear becausewe redirect to Home Page by Selecting FAQs..
![image](https://github.com/user-attachments/assets/46aab82a-2c41-4cc4-a6cc-c86b8473944b)

### Solution is that we have to display Hactoberfest details in HomePage.. No Need for navigate('/hacktoberfest2024');

**Comment by Meetpidev** [comment]
@soni-shashan And In that mini-navbar... user maybe think that Home icon is for Home page..(redirect to Home Page).. but actually its not for Home page.. its for to scrollUp in only when we are hactoberfest section.. need to fix it..

### Solution: We should Remove this Home icon. Because in Navbar there is option for Home Page.. and In hactoberfest section for scrollingUp we simply put Upward error.. inplace of this Home Icon..

**Comment by jalaym825** [comment]
replaced with hacktoberfest icon
