### ISSUE TITLE
Update Frontend to Fetch Dynamic Stats from `/api/stats`

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#12]
The current frontend for displaying stats in our using static data. We need to update it so that it fetches dynamic stats from the backend endpoint `/api/stats`.

### Requirements
- Modify the existing stats component to fetch data from `/api/stats` instead of using static data.
- Use appropriate state management to handle the fetched data.
- Ensure that loading states are displayed while the data is being fetched.
  
### Acceptance Criteria
- The component successfully fetches data from the `/api/stats` endpoint and displays it.
- The UI handles loading states and error messages appropriately.
- The implementation maintains the current design and structure of the application.

### Additional Notes
- Ensure that the data displayed matches the structure returned by the `/api/stats` endpoint.
- Consider responsiveness and accessibility in the implementation.

**Comment by A-4-Atom** [comment]
Hi, Can you assign it to me please?
I can try implementing this feature.
@jalaym825

**Comment by jalaym825** [comment]
Hey @A-4-Atom 
Currently no /api/stats is implemented from backend side, it's already a listed issue in backend repo. You can solve that first and then after this one.

**Comment by A-4-Atom** [comment]
@jalaym825 okay, i'll work on that first and come back to this issue later.

**Comment by jalaym825** [comment]
ok, assigning this issue to you. 
comment on [backend issue](https://github.com/clubgamma/club-gamma-backend/issues/5) also, so will also assign that issue to you.

**Comment by jalaym825** [comment]
@A-4-Atom can you start working on it now?

**Comment by A-4-Atom** [comment]
@jalaym825 yeah, i'll start working on it now. this shouldn't take a lot of time.
