### ISSUE TITLE
Number of PRs

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/club-gamma-frontend#139]
### Here we should also display the total number of PRs based on the filters.. 

![image](https://github.com/user-attachments/assets/032ec937-11ac-48b8-bb35-a0c6e1f8e35d)

**Comment by Meetpidev** [comment]
@jalaym825 Can I work on it ?

**Comment by Meetpidev** [comment]
Total nummber of PR.. based on filter.. we can put in before filter option..  like if we select bug in filter then its show that how many prs that have bug merged ?

**Comment by jalaym825** [comment]
ya, I got you. but you can annotate on ss and tell me the exact place where can we show the number of filter based prs?
in filter menu?

**Comment by Meetpidev** [comment]
in filter itself.. like Bug (4) etc..

**Comment by jalaym825** [comment]
ok, do it!

**Comment by jalaym825** [comment]
fixed in #140
