### ISSUE TITLE
Open Links in a New Tab in 'Contact Us' Section

### ISSUE THREAD

**Issue by hival01** [clubgamma/club-gamma-frontend#16]
Modify the links in the 'Contact Us' section so that they open in a new tab when clicked, enhancing user experience.

**Comment by Rishabh32700** [comment]
@hival01 i can take this can u plz assign this to me

**Comment by Rishabh32700** [comment]
i have solved this issue and raised PR #18 can u plz merge and add hacktoberfest and hactoberfest-accepted label
