### ISSUE TITLE
Fix Leaderboard Search Functionality

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#21]
The leaderboard search feature is currently not working as expected.

### Requirements
- Investigate why the leaderboard search is not returning the expected results.
- When search input is cleared, show the 1st page of leaderboard.

### Acceptance Criteria
- The search results endpoint returns the correct data based on the search query.

### Additional Notes
- Ensure no breaking changes to the leaderboard data structure.

**Comment by Reterics** [comment]
Hi @jalaym825 ,

The **/leaderboard?page=${page}&limit=${limit}** API endpoint returns the contributors as an array named contributors:` {"contributors": [...]}`
![image](https://github.com/user-attachments/assets/bd2ba31c-3807-4206-9e8f-5e5603ee466d)


While the **/leaderboard/search?name=${searchTerm}&page=${page}&limit=${limit}** endpoint returns the contributors as an array named data:` {"data": [...]}`
![image](https://github.com/user-attachments/assets/76e4e846-8776-4bd5-b99f-1acd0e9b3bc0)

This causes an error in LeaderBoard.jsx line 85: [/src/Pages/LeaderBoard.jsx](https://github.com/clubgamma/club-gamma-frontend/blob/01ea59488c9c1c80bc0fa0f1e4f20276eecf2e32/src/Pages/LeaderBoard.jsx#L85)
![image](https://github.com/user-attachments/assets/62cf1311-9ce3-4ebb-a4eb-8e8eacad3487)


I am happy to update and review the Leaderboard search for more issues if you assign me for this ticket.

**Comment by Reterics** [comment]
The most futureproof solution was to update the backend to have only one filter endpoint providing only one format of response, so the frontend needed only minor modifications.
