### ISSUE TITLE
navbar

### ISSUE THREAD

**Issue by Shrutibansal22** [clubgamma/club-gamma-frontend#23]
I would love to add little more css to navbar.
indly assign me this issue under hacktober-fest 2024.

**Comment by jalaym825** [comment]
assigned the issue to you.
can you be more specified about what you want to add/update in navbar?

**Comment by Shrutibansal22** [comment]
Sir i would like to add hover effect.Like on hovering background colour should be changed.
![image](https://github.com/user-attachments/assets/f1297d60-79c1-4992-8f27-ad6a3ae431e9)
Want to change like this.

**Comment by jalaym825** [comment]
I think this is not really needed. but you can try and show me once, if it matches to the theme we'll merge the pr.

**Comment by Shrutibansal22** [comment]
ok sir

**Comment by jalaym825** [comment]
any updates..? @Shrutibansal22
