### ISSUE TITLE
Display Error Message When Profile Does Not Exist in `/profile/:username`

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#26]
Currently, when navigating to `/profile/:username`, if the frontend receives an error (such as a 404 or user not found), no clear error message is displayed. The user should be informed that the profile does not exist.

### Requirements
- Update the frontend logic in the `/profile/:username` route to handle errors when the profile is not found.
- If an error is received (e.g., 404), display a user-friendly error message stating that the profile does not exist.
- Ensure the error message is styled consistently with the rest of the UI.

### Acceptance Criteria
- When an error occurs while fetching the profile data, an error message saying "Profile does not exist" is displayed.
- The error message should be clear and appropriately styled.
- The rest of the application should function normally without any UI disruptions.

### Additional Notes
- Test the error handling for various edge cases (e.g., invalid usernames, profile not found).
- Ensure the error page or message is responsive and works on different screen sizes.

**Comment by pranjalee30** [comment]
Hey @jalaym825 I want to work on this please assign this to me.

**Comment by jalaym825** [comment]
> Hey @jalaym825 I want to work on this please assign this to me.

Done, assigned.

**Comment by jalaym825** [comment]
@pranjalee30 any updates?

**Comment by jalaym825** [comment]
@pranjalee30 removing you from the issue. if you want to work lmk.

**Comment by jalaym825** [comment]
> hey, I can work on this issue, could you assign this to me?

Done!

**Comment by jalaym825** [comment]
@opbot-xd no updates from you, removing from issue.

**Comment by opbot-xd** [comment]
@jalaym825 raised a PR for this issue.
