### ISSUE TITLE
open user profile from leaderboard

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#27]
add link of user's profile in leaderboard

**Comment by Durga-prasad-1** [comment]
please assign this task to me .

**Comment by jalaym825** [comment]
> please assign this task to me .

Done!! You can work on this issue now!

**Comment by jalaym825** [comment]
@Durga-prasad-1 removing you from issue. Can ping me if you still want to work.

**Comment by MitM123** [comment]
Can assign task to me @jalaym825
