### ISSUE TITLE
Project contributer section

### ISSUE THREAD

**Issue by Adeesh-bode** [clubgamma/club-gamma-frontend#28]

**Comment by jalaym825** [comment]
@Adeesh-bode provide some description for the issue.

**Comment by jalaym825** [comment]
I think I got it. 
option to show project contributors. good idea. share implementation thoughts. also we need to make api for this.

**Comment by Adeesh-bode** [comment]
1. API Endpoints:

GET /repos/{owner}/{repo}/contributors – To fetch the list of contributors.

2. Data Processing:

Process the retrieved data to generate meaningful insights

3. Designing the Contribution Section:




I have hitted that endpoint - got the contributors , just have to implement:::




![Screenshot (28)](https://github.com/user-attachments/assets/a698ef38-e404-459c-95c7-9a08a9bbb631)

**Comment by jalaym825** [comment]
> 1. API Endpoints:
> 
> GET /repos/{owner}/{repo}/contributors – To fetch the list of contributors.
> 
> 2. Data Processing:
> 
> Process the retrieved data to generate meaningful insights
> 
> 3. Designing the Contribution Section:
> 
> I have hitted that endpoint - got the contributors , just have to implement:::
> 
> ![Screenshot (28)](https://private-user-images.githubusercontent.com/121815318/377600546-a698ef38-e404-459c-95c7-9a08a9bbb631.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyMTA0NTIsIm5iZiI6MTcyOTIxMDE1MiwicGF0aCI6Ii8xMjE4MTUzMTgvMzc3NjAwNTQ2LWE2OThlZjM4LWU0MDQtNDU5Yy05NWM3LTlhMDhhOWJiYjYzMS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOFQwMDA5MTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MzQ4YWU2ZGFjYTRiZmZkZDEwMmE4ODEzYjkyNDQ0OTMwMjRkMjcxZmUxNmIxYTViZDFkMTQxYWQ5ODI2ODVlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.NT5gV8Tu26r98OV-HCU6s8X1p_gXEUUvmxyvQP0guBc)

We won't be using github api to get contributors. Instead look at this issue once. https://github.com/clubgamma/club-gamma-backend/issues/15

**Comment by Adeesh-bode** [comment]
Should We show only major contributors like top3 , generally top 3 are only shown

**Comment by jalaym825** [comment]
what I want is
for each project there should be a list of contributors, we've api for that /api/projects/contributors/reponame

**Comment by vasu-CE** [comment]
what you want for display contributors , redirect new page or display bottom of the card

**Comment by vasu-CE** [comment]
which information give this API "/api/projects/contributors/reponame" so that i make frontend based on that

**Comment by jalaym825** [comment]
> which information give this API "/api/projects/contributors/reponame" so that i make frontend based on that

https://pastebin.com/rTYCTVnU
