### ISSUE TITLE
feat: Add team section

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#29]
We need to create a dedicated team section for **Club Gamma** to showcase the team members involved in various roles and contributions. This section should have a clean and consistent design that aligns with the overall look and feel of the website.

### Requirements
- Create a new section that lists all the team members, their roles, and any relevant information (e.g., photos, positions, social media links).
- Ensure the section is responsive and mobile-friendly.
- Include a way to easily update team member information by fetching data dynamically from a `team.json` file.
- The design should be consistent with the rest of the site, using the same color scheme, fonts, and layout patterns.

### Additional Notes
- Create a `JSON` folder in the repository.
- Inside the `JSON` folder, create a `team.json` file to store team member information.
- Fetch the `team.json` data by sending get request to `https://raw.githubusercontent.com/clubgamma/club-gamma-frontend/refs/heads/main/JSON/team.json` to dynamically load the team information on the section.
- Test the section layout across different screen sizes to ensure a good user experience.

### Acceptance Criteria
- A new `Team` option in navbar.
- Each team member is displayed with their name, role, and photo.
- The section is responsive and works well on both desktop and mobile devices.
- The team section follows the current design language of the website.
- Team member data is fetched dynamically from the `team.json` file via GitHub's API.

**Comment by saadii00** [comment]
Hey kindly assign it to me. I would love to contribute to it.

**Comment by jalaym825** [comment]
@saadii00 done, also read the description once again, updated*

**Comment by Shivam-Amin** [comment]
Is anyone working on this issue?

**Comment by MitM123** [comment]
this task assign me @jalaym825

**Comment by jalaym825** [comment]
@Shivam-Amin can you work on #11
