### ISSUE TITLE
feat: add events section

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#30]
We need to create dedicated pages for each year of events for **Club Gamma** that allows users to view events from different years. Users should be able to select a year from a dropdown in the navbar, which will navigate them to a specific page displaying the events that took place in that year.

### Requirements
- Add a **Dropdown** option in the navbar to select the year.
- Each year selected from the dropdown should navigate the user to a new page that shows all events done in that specific year.
- Ensure each events page is responsive and mobile-friendly.
- Include an easy way to update event information by fetching data dynamically from a `events.json` file.
- The design should be consistent with the rest of the site, using the same color scheme, fonts, and layout patterns.

### Additional Notes
- Fetch the `events.json` data by sending a GET request to `https://raw.githubusercontent.com/clubgamma/club-gamma-frontend/refs/heads/main/JSON/events.json` to dynamically load event information for the selected year.
- For each year, send a request to `https://raw.githubusercontent.com/clubgamma/club-gamma-frontend/refs/heads/main/JSON/markdowns/{filename}` to get the relevant markdown content.
- Ensure the layout for each events page works well on both desktop and mobile devices.

### Acceptance Criteria
- A **Dropdown** in the navbar allows users to select a year.
- After selecting a year, the user is navigated to a new page showing events from that year.
- Each yearly events page is responsive and consistent with the current website design.
- Event data is fetched dynamically from the `events.json` file via GitHub's API.

**Comment by saadii00** [comment]
Hey kindly assign it to me. I would love to contribute to it.
