### ISSUE TITLE
Contact Us Session

### ISSUE THREAD

**Issue by Dhavisco** [clubgamma/club-gamma-frontend#32]
Based on my observation, the size of icons at the Contact Us session is big for mobile view (smaller screens)

I would like to contribute to this project by fixing it.
![image](https://github.com/user-attachments/assets/e0b0ba37-bf7a-403c-bc24-ae02f8cc508a)

**Comment by jalaym825** [comment]
go ahead! assigned the issue.

**Comment by Dhavisco** [comment]
Thank you.

I will work on it and provide an update.
