### ISSUE TITLE
Navbar background stays blue and scrolling disabled after returning from Event Details

### ISSUE THREAD

**Issue by soni-shashan** [clubgamma/club-gamma-frontend#38]
### When we click `View Details`, the background turns blue as expected. However, after clicking the `Back` button, the event details disappear, but the navbar remains blue. Additionally, the page automatically navigates to the home page, and scrolling becomes disabled.

![Screenshot_20241019_180542_Chrome.png](https://github.com/user-attachments/assets/1493fc3a-b428-4918-b54f-dbdd6961a3ce)

**Comment by jalaym825** [comment]
Want to work on it? @soni-shashan

**Comment by MitM123** [comment]
Can you assign this task to me @jalaym825

**Comment by soni-shashan** [comment]
done

**Comment by jalaym825** [comment]
> done

Shashan, issue is already solved by @MitM123 .
