### ISSUE TITLE
EventListner on card

### ISSUE THREAD

**Issue by shubhamkumaar** [clubgamma/club-gamma-frontend#51]
![image](https://github.com/user-attachments/assets/60a973f1-ac6d-437b-8d2a-63785b8f0a9c)

Before: We have to click that GitHub button to redirect.
After: Click anywhere on the card you will be redirected.

I can redirect these cards to their respective GitHub repository.

**Comment by vasu-CE** [comment]
Completed

**Comment by shubhamkumaar** [comment]
Hey can you add hactoberfest and gssoc  labels

**Comment by vasu-CE** [comment]
No i can't

**Comment by PriyanshuValiya** [comment]
@shubhamkumaar Assign me this issue, if any work is remain..

**Comment by jalaym825** [comment]
@shubhamkumaar start working on it. also repo is not participating in gssoc, it's for hacktoberfest only.
