### ISSUE TITLE
Display in Leader board

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/club-gamma-frontend#64]
We should display that contributer that whose atleast 1 PR merged in any of club gamma project.. current system display all the members. some of them dont contributing to club gamma project.. "Newcomer" label is meaningless because we can labeled as "contributer" whose atleast one PR merged..

**Comment by jalaym825** [comment]
@Meetpidev  In leaderboard?

**Comment by Meetpidev** [comment]
@jalaym825 Yes In Leaderboard.. in that current system also display named who dont contribut to club-gamma project.. we dont need to display their name.. we only display name in leader board whose atleat one PR is accepted...

**Comment by jalaym825** [comment]
actually, in starting there were less number of contributors, that's why.
I just need to make change in backend btw.
it's an issue of backend.

**Comment by jalaym825** [comment]
done! fixed!
