### ISSUE TITLE
Scrollbar Suggestion

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/club-gamma-frontend#69]
There should be scrollbar in Recent Pull Requests.. because there is lots of PR display in continuous.. vertical Scrollerbar enhance user experience...

![image](https://github.com/user-attachments/assets/ad8acfe5-ffbe-4127-beb7-3d143c7bd944)

**Comment by jalaym825** [comment]
Ok, Implement.

**Comment by vasu-CE** [comment]
if he don't work on this then assign to me

**Comment by Meetpidev** [comment]
> if he don't work on this then assign to me

Im working on this..

**Comment by jalaym825** [comment]
> > if he don't work on this then assign to me
> 
> Im working on this..

any updates?

**Comment by Meetpidev** [comment]
> > > if he don't work on this then assign to me
> > 
> > 
> > Im working on this..
> 
> any updates?

Soon send you PR

**Comment by Meetpidev** [comment]
@jalaym825 We also need to add scrollbar in entire website to enhance user experience.. currently there is no scrollbar...

**Comment by Meetpidev** [comment]
@jalaym825 Should i add ??
