### ISSUE TITLE
Add UI for syncing PRs to /api/users/sync-prs in frontend

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#7]
### Description:
We need to create a **UI component** that allows users to sync their PRs by interacting with the `/api/users/sync-prs` endpoint. This will help users manage their contributions directly from the frontend.

### Tasks:
1. **UI Design**:
   - Add a button or link to trigger the sync PRs action.
   - The button should be clearly labeled (e.g., "Sync PRs").
   - Show a loading indicator while the request is in progress.

2. **API Integration**:
   - Connect the UI to the `/api/users/sync-prs` route.
   - Ensure the request is authenticated (use any available token or session handling).
   - Handle any errors or rate limiting responses gracefully (e.g., show a message if the user is rate-limited).

3. **User Feedback**:
   - Display success or failure messages based on the result of the sync request.
   - Optionally, show a summary of synced PRs after the operation completes.

### Notes:
- Ensure proper error handling for failed requests (network issues, authentication failures, etc.).
- Follow existing UI/UX patterns for consistency.
- Add relevant tests to cover this new functionality.

**Comment by opbot-xd** [comment]
could you assign this to me?

**Comment by mzf11125** [comment]
Hey, I think I can help you with this. Please assign me, thanks

**Comment by jalaym825** [comment]
fixed in #77
