### ISSUE TITLE
Fix: need pading in stats card for mobile view

### ISSUE THREAD

**Issue by jalaym825** [clubgamma/club-gamma-frontend#73]
![Screenshot_20241024_170208_Chrome](https://github.com/user-attachments/assets/b6e9bdd5-54d3-4e40-b934-3c075a0c6895)

**Comment by Ayushkalathiya** [comment]
can you assign me this task @jalaym825  ??

**Comment by mzf11125** [comment]
Hey, I think I can help you with this. Please assign me, thanks

**Comment by jalaym825** [comment]
fixed in #74
