### ISSUE TITLE
[FEAT] : Add E-Mail Form in Contact Us

### ISSUE THREAD

**Issue by PriyanshuValiya** [clubgamma/club-gamma-frontend#81]
In this feature, we will add contact us email form, from this feature user can mail their query via email direct from website.

**Previous Work**
![Screenshot 2024-10-25 125504](https://github.com/user-attachments/assets/650e605a-f230-4970-b113-77b18e9c14a5)

**Comment by ShivamP0077** [comment]
@PriyanshuValiya  i want to work on that

**Comment by Krishnap2k4** [comment]
Hi @PriyanshuValiya, Would you please assign this issue to me? Would love to work on this.
