### ISSUE TITLE
Facing issue while running project

### ISSUE THREAD

**Issue by Meetpidev** [clubgamma/club-gamma-frontend#98]
### Facing issue while running frontend..

![image](https://github.com/user-attachments/assets/69b939d1-e719-430d-be1b-e660e90174f0)

### includes in env file even though its shows error

![image](https://github.com/user-attachments/assets/7e599767-2082-4849-a0ac-0acadc1fa12e)

**Comment by Meetpidev** [comment]
@jalaym825 Requested to help me

**Comment by jalaym825** [comment]
@Meetpidev you need to add the redirect uri in github application settings also.

**Comment by jalaym825** [comment]
can you try `npm i` once and then start frontend

**Comment by Meetpidev** [comment]
> can you try `npm i` once and then start frontend

### I tried it but it show me the same error..

![image](https://github.com/user-attachments/assets/04316909-4984-42de-ba9a-b2e8423b1a5e)

### After refresh the page..
![image](https://github.com/user-attachments/assets/1545afe0-ecd3-41ec-92eb-cb51a60394a2)
